//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.BILLs = new HashSet<BILL>();
            this.BILLs1 = new HashSet<BILL>();
            this.BOOKROOMs = new HashSet<BOOKROOM>();
            this.BOOKROOMs1 = new HashSet<BOOKROOM>();
        }
    
        public string CUS_ID { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string SEX { get; set; }
        public Nullable<byte> CUS_IDENTITY { get; set; }
        public string PHONE { get; set; }
        public string CAREER { get; set; }
        public string NATIONALITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKROOM> BOOKROOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKROOM> BOOKROOMs1 { get; set; }
    }
}
