//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.HOTELSERVICEs = new HashSet<HOTELSERVICE>();
            this.HOTELSERVICEs1 = new HashSet<HOTELSERVICE>();
            this.USERS = new HashSet<USER>();
            this.USERS1 = new HashSet<USER>();
        }
    
        public string STAFF_ID { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string SEX { get; set; }
        public Nullable<byte> STAFF_IDENTITY { get; set; }
        public string PHONE { get; set; }
        public string STAFF_ADDRESS { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public string POSITION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTELSERVICE> HOTELSERVICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTELSERVICE> HOTELSERVICEs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS1 { get; set; }
    }
}
